swagger: '2.0'
info:
  title: Energy Measurement API
  description: 'Company name, project name, purpose of the api creation, date of last update, sometimes code author name.'
  version: 2.0.0
host: api.yourcompany.com
schemes:
  - https
basePath: /v2
produces:
  - application/json
securityDefinitions:
  basicAuth:
    type: basic
security:
  - basicAuth: []
paths:
  '/consumed':
    post:
      summary: Create a new consuming asset
      description: ''
      tags:
        - Energy Consumer
      parameters:
         - $ref: '#/definitions/Device'
         - $ref: '#/definitions/MeasuredEnergy'
      responses:
        '200':
          $ref: '#/definitions/Status'
        '400':
          $ref: '#/responses/BadRequest'
        '401':
          $ref: '#/responses/Unauthorized'
      
  '/consumed/{deviceId}':
    get:
      summary: Retrieve consumed energy
      description: Energy consumed measured in Mega Watts during a certain period.
      tags:
        - Energy Consumer
      parameters:
        - name: deviceId
          in: path
          description: EnergyAsset identification number
          required: true
          type: integer
          format: int32
        - name: limit
          in: query
          description: How many items to return at one time (max 10)
          required: true
          default: 5
          type: integer
          format: int32
        - name: start
          in: query
          description: 'Date in RFC 3339 format. ie. 2018-03-14T17:11:19+00:00'
          required: true
          default: last_hour
          type: string
          format: "date-time"
        - name: end
          in: query
          description: 'Date in RFC 3339 format. ie. 2018-03-14T17:12:20+00:00'
          required: true
          default: now
          type: string
          format: "date-time"
        - name: page
          in: query
          description: Page number
          required: false
          default: 0
          type: integer
      responses:
        '200':
          $ref: '#/definitions/Status'
        '400':
          $ref: '#/responses/BadRequest'
        '401':
          $ref: '#/responses/Unauthorized'
        '404':
          $ref: '#/responses/NotFound'
    put:
      summary: Publish consumed energy
      tags:
        - Energy Consumer
      parameters:
        - name: deviceId
          in: path
          description: EnergyAsset identification number
          required: true
          type: integer
          format: int32
        - name: energy
          in: query
          type: number
          description: Registered in Mega Watts
        - name: measurement_time
          in: query
          type: string
          format: "date-time"
          description: 'Time of measurement in the device, in RFC 3339 format. ie. 2018-03-14T17:12:20+00:00'
      responses:
        '200':
          $ref: '#/definitions/Status'
        '400':
          $ref: '#/responses/BadRequest'
        '401':
          $ref: '#/responses/Unauthorized'
        '404':
          $ref: '#/responses/NotFound'
    delete:
      summary: Remove published energy
      tags:
        - Energy Consumer
      parameters:
        - name: deviceId
          in: path
          description: EnergyAsset identification number
          required: true
          type: integer
          format: int32
        - name: start
          in: query
          description: 'Date in RFC 3339 format. ie. 2018-03-14T17:11:19+00:00'
          required: true
          default: last_hour
          type: string
          format: "date-time"
        - name: end
          in: query
          description: 'Date in RFC 3339 format. ie. 2018-03-14T17:12:20+00:00'
          required: true
          default: now
          type: string
          format: "date-time"
      responses:
        '200':
          $ref: '#/definitions/Status'
        '400':
          $ref: '#/responses/BadRequest'
        '401':
          $ref: '#/responses/Unauthorized'
        '404':
          $ref: '#/responses/NotFound'

  '/produced':
    post:
      summary: Create a new producing asset
      description: ''
      tags:
        - Energy Producer
      parameters:
         - $ref: '#/definitions/Device'
         - $ref: '#/definitions/MeasuredEnergy'
      responses:
        '200':
          description: An array of measured energy
          schema:
            type: array
            items:
              $ref: '#/definitions/MeasuredEnergyOnDevice'
        '400':
          $ref: '#/responses/BadRequest'
        '401':
          $ref: '#/responses/Unauthorized'

  '/produced/{deviceId}':
    get:
      summary: Retrieve produced energy
      description: Energy produced measured in Mega Watts during a certain period.
      tags:
        - Energy Producer
      parameters:
        - name: deviceId
          in: path
          description: EnergyAsset identification number
          required: true
          type: integer
          format: int32
        - name: limit
          in: query
          description: How many items to return at one time (max 10)
          required: true
          default: 5
          type: integer
          format: int32
        - name: start
          in: query
          description: 'Date in RFC 3339 format. ie. 2018-03-14T17:11:19+00:00'
          required: true
          default: last_hour
          type: string
          format: "date-time"
        - name: end
          in: query
          description: 'Date in RFC 3339 format. ie. 2018-03-14T17:12:20+00:00'
          required: true
          default: now
          type: string
          format: "date-time"
        - name: page
          in: query
          description: Page number
          required: false
          default: 0
          type: integer
      responses:
        '200':
          description: An array of measured energy
          schema:
            type: array
            items:
              $ref: '#/definitions/MeasuredEnergyOnDevice'
        '400':
          $ref: '#/responses/BadRequest'
        '401':
          $ref: '#/responses/Unauthorized'
        '501':
          $ref: '#/responses/NotImplemented'
    put:
      summary: Publish consumed energy
      tags:
        - Energy Producer
      parameters:
        - name: deviceId
          in: path
          description: EnergyAsset identification number
          required: true
          type: integer
          format: int32
        - name: energy
          in: query
          type: number
          description: Registered in Mega Watts
        - name: measurement_time
          in: query
          type: string
          format: "date-time"
          description: 'Time of measurement in the device, in RFC 3339 format. ie. 2018-03-14T17:12:20+00:00'
      responses:
        '200':
          $ref: '#/definitions/Status'
        '400':
          $ref: '#/responses/BadRequest'
        '401':
          $ref: '#/responses/Unauthorized'
        '404':
          $ref: '#/responses/NotFound'
    delete:
      summary: Remove published energy
      tags:
        - Energy Producer
      parameters:
        - name: deviceId
          in: path
          description: EnergyAsset identification number
          required: true
          type: integer
          format: int32
        - name: start
          in: query
          description: 'Date in RFC 3339 format. ie. 2018-03-14T17:11:19+00:00'
          required: true
          default: last_hour
          type: string
          format: "date-time"
        - name: end
          in: query
          description: 'Date in RFC 3339 format. ie. 2018-03-14T17:12:20+00:00'
          required: true
          default: now
          type: string
          format: "date-time"
      responses:
        '200':
          $ref: '#/definitions/Status'
        '400':
          $ref: '#/responses/BadRequest'
        '401':
          $ref: '#/responses/Unauthorized'
        '404':
          $ref: '#/responses/NotFound'
responses:
  Unauthorized:
    description: Authentication information is missing or invalid
    headers:
      WWW_Authenticate:
        type: string
  MethodNotAllowed:
    description: Method not allowed. Check headers for allowed methods.
    headers:
      Access-Control-Allow-Methods:
        type: string
  NotImplemented:
    description: Endpoint not implemented
  BadRequest:
    description: Limit must be non-zero positive integer | Dates must be in RFC 3339 format | Start date must be higher than end date
  NotFound:
    description: The asset with id has not been found on the server
definitions:
  Device:
    description: Energy measuring device
    type: object
    properties:
      manufacturer:
        type: string
        description: EnergyAsset Manufacturer
      model:
        type: string
        description: EnergyAsset Model
      serial_number:
        type: string
        description: EnergyAsset Serial Number
      latitude:
        type: number
        description: Geolocation point latitude
      longitude:
        type: number
        description: Geolocation point latitude
      energy_unity:
        type: string
        description: 'Unit of energy measurement. MUST be "joules", "watt_hour", "kilowatt_hour", "megawatt_hour" or "gigawatt_hour".'
      is_accumulated:
        type: boolean
        description: 'Defines if the provided energy data is accumulated or not. It is common that solar panels only provide energy generated at the measurement time, not the accumulated value like a domestic energy energy_meter, for example.'
  MeasuredEnergy:
    description: Energy measured at a certain time.
    type: object
    properties:
      energy:
        type: number
        description: Registered in Mega Watts
      measurement_time:
        type: string
        format: "date-time"
        description: 'Time of measurement in the device, in RFC 3339 format. ie. 2018-03-14T17:12:20+00:00'
  MeasuredEnergyOnDevice:
    type: object
    properties:
      page:
        type: integer
        description: Page number
      previous:
        type: string
        description: Link to previous page
      next:
        type: string
        description: Link to next page
      device_id:
        type: integer
        description: 'EnergyAsset number, for identification when there are multiple devices in the same site with only one api point.'
      device:
        $ref: '#/definitions/Device'
      measuredEnergy:
        type: array
        items:
          $ref: '#/definitions/MeasuredEnergy'
  Status:
    type: object
    required: [error]
    properties:
      error:
        type: string
        description: Name of error in case an error occured, empty otherwise
      message:
        type: string
        description: Additional status information like error message in case of error
